ARG python_version=3.6
FROM python:${python_version}
LABEL maintainer "matteo.piacentini3@studenti.unimi.it"

RUN apt-get update \
    && apt-get install -y git \
    && pip install -U pip \
    && apt-get autoremove \
    && apt-get clean

ARG backend
ARG abci_status

# When developing with Python in a docker container, we are using PYTHONBUFFERED
# to force stdin, stdout and stderr to be totally unbuffered and to capture logs/outputs
ENV PYTHONUNBUFFERED 0

ENV MULTICHAINDB_DATABASE_PORT 8529
ENV MULTICHAINDB_DATABASE_BACKEND $backend
ENV MULTICHAINDB_SERVER_BIND 0.0.0.0:9984
ENV MULTICHAINDB_WSSERVER_HOST 0.0.0.0
ENV MULTICHAINDB_WSSERVER_SCHEME ws

ENV MULTICHAINDB_WSSERVER_ADVERTISED_HOST 0.0.0.0
ENV MULTICHAINDB_WSSERVER_ADVERTISED_SCHEME ws

ENV MULTICHAINDB_TENDERMINT_PORT 26657

ENV MULTICHAINDB_CI_ABCI ${abci_status}

RUN mkdir -p /usr/src/app
COPY . /usr/src/app/
WORKDIR /usr/src/app
RUN pip install -e .[dev]
RUN multichaindb -y configure
